
export const ADD_REPORT_ITEM = 'ADD_REPORT_ITEM';

export const DEL_REPORT_ITEM = 'DEL_REPORT_ITEM';

export const CLEAR_REPORT_ITEMS = 'CLEAR_REPORT_ITEMS';

export const ADD_CONTROL_ITEM = 'ADD_CONTROL_ITEM';

export const DEL_CONTROL_ITEM = 'DEL_CONTROL_ITEM';

export const CLEAR_CONTROL_ITEM = 'CLEAR_CONTROL_ITEM';
